### ISSUE TITLE
Libpng warning: out of memory. 

### ISSUE THREAD

**Issue by counterfitninja** [bedrock-viz/bedrock-viz#1]
I have just tried to run this latest version against one of my maps and im getting this: 

![{79E1FC85-2B8A-4856-A8FE-34DE8A3A0032} png](https://user-images.githubusercontent.com/4258903/70621150-d06bc680-1c10-11ea-97a0-c1d1b8fa45a0.jpg)

**Comment by jasper-wan** [comment]
I think I may need more information to determine the problem. Could you provide the full log? And how much memory does this computer have?

**Comment by counterfitninja** [comment]
I was only running 4gb of RAM on the server, which was sufficient previously, but i have upped that to 16Ggb to give me some head room and it completes. However it does not seem to output the files. 

The command im using is as follows: 

bedrock-viz.exe --db "C:\bedrock\bedrock-server-1.14.0.9\worlds\Bedrock level"  --out c:\temp --html-all --verbose --log c:\temp\oupput.txt

The output file is created and i have attached it here and its seems like the files should be created. 
![image](https://user-images.githubusercontent.com/4258903/70698137-bee0f800-1cbe-11ea-82c9-55b9d6ddc941.png)
[oupput.txt](https://github.com/bedrock-viz/bedrock-viz/files/3954803/oupput.txt)

**Comment by counterfitninja** [comment]
Ok looks like i was not reading the instructions properly. The output file need labeling. Once i had done that things are working as expected once i had upped the memory.
