### ISSUE TITLE
Discord Server

### ISSUE THREAD

**Issue by counterfitninja** [bedrock-viz/bedrock-viz#100]
Im Really surprised there is no discord server attached to this project. Just so the many people that are probably watching it can chat about issues they face and maybe other devs can show case their own branches when they develop features. 

Is this something anyone would be interested in ?

**Comment by cabbey** [comment]
Hold off on creating one for a bit please....

**Comment by counterfitninja** [comment]
Thankfully i dont have the patience to run another server and i think it would need to be endorsed by the team anyway. Hopefully you have something in mind as it would be good be able to properly chat to people using it and things they have done outside of github

**Comment by cabbey** [comment]
While I figure out how to get it into the GitHub summary: https://discord.gg/ghAFUehs
