### ISSUE TITLE
[BUG] "Check for Update" returns an older version when on the latest pull from master

### ISSUE THREAD

**Issue by phunni** [bedrock-viz/bedrock-viz#103]
**Describe the bug**
If I click on "Check for bedrock-viz update" in the options menu it tells me that I'm on version 0.1.2 and that 0.1.3 is now available. I didn't install bedrock-viz from a release, but rather by simply cloning the master branch. I would've assumed that the latest master would return either the latest version or it would return a version later still. Or, perhaps, something else.

**To Reproduce**
1. Check out the latest master branch.
2. Build.
3. Run bedrock-viz on a MC game.
4. Open the generated map.
2. Go to 'Options'
2. Click on 'Check for Bedrock Viz update...'
3. View the reported version number as 0.1.2 and be told that you're out of date - despite having the latest master branch.

**Expected behavior**
I would've assumed that the latest master would return either the latest version or it would return a version later still. Or, perhaps, something else.

**Screenshots**
![screenshot](https://user-images.githubusercontent.com/11048658/109850950-fd0f6200-7c4a-11eb-8e49-e9c7d36ae301.png)

**Environment Information:**
 - OS: Linux
 - bedrock-viz version: master
 - Browser (for frontend issues): Chrome

**Comment by cabbey** [comment]
oh my. I didn't realize that code was pulling from `master`... But more importantly, 0.1.3 didn't update the version field that's hidden away in a corner. I'll patch that for 0.1.4 and see if I can fix the JS to not be looking at master.  Not sure how best to handle the case of folks pulling from git.... will think on that.
