### ISSUE TITLE
[  error] LevelDB operation returned status=Corruption: 1 missing files;  [BUG] 

### ISSUE THREAD

**Issue by Escrimark** [bedrock-viz/bedrock-viz#104]
When called, bedrock-viz.exe will find the level.dat but not the * .ldb files in the db directory.

Although I have the following three ldb files:
003751.ldb 003753.ldb and 003754.ldb

Steps to reproduce the behavior (Bedrock Server 1.16.201.03 : : bedrock-viz_v0.1.3_win64)
1. Go to cmd. exe
2. Execute bedrock-viz.exe --db "Minecraft/worlds/Bedrock level" --out out1 --html-most
[   info] Loading xml from (data/bedrock_viz.xml)
[   info] Loading config from (data/bedrock_viz.cfg)
[   info] parseLevelFile: name=Minecraft/worlds/Bedrock level/level.dat version=8 len=2201
[   info]   Found World Spawn: x=44 y=32767 z=4
[   info] levelname.txt: Level name is 'Bedrock level'
[   info] DB Open: dir=Minecraft/worlds/Bedrock level
[   info] DB Open Status: Corruption: 1 missing files; e.g.: Minecraft/worlds/Bedrock level/db/003871.ldb (block_size=4096 bloom_filter_bits=10)
[  error] LevelDB operation returned status=Corruption: 1 missing files; e.g.: Minecraft/worlds/Bedrock level/db/003871.ldb

**Expected behavior**
Loading of the three existing -ldb files

**Screenshots**

**Environment Information:**
 - OS: Windows 10
 - bedrock-viz version: 1.16.201.3 (Linux)
 - Browser: None
 - Build toolchain information:  None
 
![BedrockError](https://user-images.githubusercontent.com/77208686/110211728-37ba0a00-7e98-11eb-88bf-ea22e8e27c2e.PNG)

**Comment by cabbey** [comment]
As noted in your screen shot, the file it was looking for 003**87**1.ldb is not present. Not sure how you got the database there, but it appears to be incomplete or corrupt.
