### ISSUE TITLE
Is this project still alive?

### ISSUE THREAD

**Issue by phunni** [bedrock-viz/bedrock-viz#105]
Or is it dead and unsupported?

**Comment by cmbkla** [comment]
At this point, I would support a fork-off with new administration, and I volunteer to help actively monitor the pull requests on a scheduled basis. I am very interested in expanding and improving the UI, but I'm afraid I don't have the chops to mess with that backend, else I would fork off on my own.

**Comment by counterfitninja** [comment]
Surprised things appear quite so dead. There was a flurry of activity 6 months ago and it looks like quite a few new people were participating, but that seems to have stopped. I wonder if the Caves and Cliffs update will being people back. Mind you i have been playing with Geyser for Java and Bedrock cross play and the maps there are something else, i wish we could do something similar on Bedrock

**Comment by tomnolan** [comment]
For whatever it's worth, I do plan on coming back to this but between a new baby and a new job, the last 10 months have been a bit crazy, so I haven't been paying much attention. I'm planning on changing that soon™.

**Comment by GRMule** [comment]
Understandable. Would you consider making myself or someone else a
contributor so that we can keep the ball moving when you don't have the
time?

**Comment by phunni** [comment]
@tomnolan congratulations on the new baby and job! Exhausting times :-)

**Comment by cabbey** [comment]
@GRMule I noticed it only took a few solid PRs before they offered me commit access. ;)

Much like Tom... I got slammed at work after the holidays and haven't had much time to play, let alone hack on the map generation. I do hope to be able to get the block updates in as soon as we see a working 1.17 bedrock client I can enlist my son with into building a test world with the new types.

**Comment by counterfitninja** [comment]
Good to see a little rejuvenation on here. Love the app and dont want it to go stale.

**Comment by juliankay** [comment]
I'd love to continue to use the app in 1.17 and willing to help where I can 👍

**Comment by cabbey** [comment]
going to close this as "answered". ;)
