### ISSUE TITLE
[BUG] Unknown uname

### ISSUE THREAD

**Issue by Plidian** [bedrock-viz/bedrock-viz#110]
When I run the html-all against my folder it provides warning indicating that there are unknown names for several objects.

STR
1. Have a world where one of your chests contains dyes, a cod bucket or an oak sign
2. Execute the  bedrock-viz using the flags --db, --outdir and --html-all E.G. >bedrock-viz --db "\data\AchieveMCWORLD\SZx4YOZMAAA=" --outdir \Data\AchieveMCWORLD\HTMLMap --html-all
3. Wait for the process to finish
4. Notice errors in the command window

**Expected behavior**
Processing of the map finishes without errors

My particular list follows

[warning] Unknown uname: minecraft:black_dye
[warning] Unknown uname: minecraft:blue_dye
[warning] Unknown uname: minecraft:bone_meal
[warning] Unknown uname: minecraft:charcoal
[warning] Unknown uname: minecraft:cod_bucket
[warning] Unknown uname: minecraft:cyan_dye
[warning] Unknown uname: minecraft:filled_map
[warning] Unknown uname: minecraft:green_dye
[warning] Unknown uname: minecraft:ink_sac
[warning] Unknown uname: minecraft:lapis_lazuli
[warning] Unknown uname: minecraft:lava_bucket
[warning] Unknown uname: minecraft:light_blue_dye
[warning] Unknown uname: minecraft:light_gray_dye
[warning] Unknown uname: minecraft:lime_dye
[warning] Unknown uname: minecraft:magenta_dye
[warning] Unknown uname: minecraft:music_disc_13
[warning] Unknown uname: minecraft:music_disc_mellohi
[warning] Unknown uname: minecraft:oak_sign
[warning] Unknown uname: minecraft:orange_dye
[warning] Unknown uname: minecraft:pink_dye
[warning] Unknown uname: minecraft:purple_dye
[warning] Unknown uname: minecraft:red_dye
[warning] Unknown uname: minecraft:spruce_boat
[warning] Unknown uname: minecraft:water_bucket
[warning] Unknown uname: minecraft:white_dye
[warning] Unknown uname: minecraft:yellow_dye

I've reviewed the data information found on the wiki.  I noticed that the output.js did not have mappings for items 351, 333, 325, 358, 263, 500, and 506.  Also several of those were missing from the static/images directory
[minecraft viz errors.xlsx](https://github.com/bedrock-viz/bedrock-viz/files/6581102/minecraft.viz.errors.xlsx)
Interestingly the bedrock_viz.xml  in the /data folder does have entries for Oak Sign and boat and the ID's do match so the problem doesn't seem to be there.

**Comment by cabbey** [comment]
Most of this (maybe all?) will be fixed by PR #86 which has now landed for the next release.

**Comment by cabbey** [comment]
@Plidian can you grab v0.1.4 and see if that resolves your issues?

**Comment by Plidian** [comment]
Sadly no
[warning] Unknown uname: minecraft:amethyst_block
[warning] Unknown uname: minecraft:amethyst_cluster
[warning] Unknown uname: minecraft:amethyst_shard
[warning] Unknown uname: minecraft:black_dye
[warning] Unknown uname: minecraft:blue_dye
[warning] Unknown uname: minecraft:bone_meal
[warning] Unknown uname: minecraft:bordure_indented_banner_pattern
[warning] Unknown uname: minecraft:budding_amethyst
[warning] Unknown uname: minecraft:calcite
[warning] Unknown uname: minecraft:charcoal
[warning] Unknown uname: minecraft:cobbled_deepslate
[warning] Unknown uname: minecraft:cod_bucket
[warning] Unknown uname: minecraft:copper_block
[warning] Unknown uname: minecraft:copper_ingot
[warning] Unknown uname: minecraft:copper_ore
[warning] Unknown uname: minecraft:cut_copper
[warning] Unknown uname: minecraft:cut_copper_stairs
[warning] Unknown uname: minecraft:cyan_dye
[warning] Unknown uname: minecraft:deepslate
[warning] Unknown uname: minecraft:deepslate_coal_ore
[warning] Unknown uname: minecraft:deepslate_copper_ore
[warning] Unknown uname: minecraft:deepslate_diamond_ore
[warning] Unknown uname: minecraft:deepslate_emerald_ore
[warning] Unknown uname: minecraft:deepslate_gold_ore
[warning] Unknown uname: minecraft:deepslate_iron_ore
[warning] Unknown uname: minecraft:deepslate_lapis_ore
[warning] Unknown uname: minecraft:deepslate_redstone_ore
[warning] Unknown uname: minecraft:dripstone_block
[warning] Unknown uname: minecraft:filled_map
[warning] Unknown uname: minecraft:flower_banner_pattern
[warning] Unknown uname: minecraft:glow_ink_sac
[warning] Unknown uname: minecraft:glow_lichen
[warning] Unknown uname: minecraft:green_dye
[warning] Unknown uname: minecraft:infested_deepslate
[warning] Unknown uname: minecraft:ink_sac
[warning] Unknown uname: minecraft:lapis_lazuli
[warning] Unknown uname: minecraft:large_amethyst_bud
[warning] Unknown uname: minecraft:lava_bucket
[warning] Unknown uname: minecraft:light_gray_dye
[warning] Unknown uname: minecraft:lightning_rod
[warning] Unknown uname: minecraft:lime_dye
[warning] Unknown uname: minecraft:lit_deepslate_redstone_ore
[warning] Unknown uname: minecraft:magenta_dye
[warning] Unknown uname: minecraft:medium_amethyst_bud
[warning] Unknown uname: minecraft:music_disc_13
[warning] Unknown uname: minecraft:music_disc_mellohi
[warning] Unknown uname: minecraft:oak_boat
[warning] Unknown uname: minecraft:oak_sign
[warning] Unknown uname: minecraft:orange_dye
[warning] Unknown uname: minecraft:pink_dye
[warning] Unknown uname: minecraft:pointed_dripstone
[warning] Unknown uname: minecraft:purple_dye
[warning] Unknown uname: minecraft:raw_copper
[warning] Unknown uname: minecraft:raw_copper_block
[warning] Unknown uname: minecraft:raw_iron
[warning] Unknown uname: minecraft:red_dye
[warning] Unknown uname: minecraft:small_amethyst_bud
[warning] Unknown uname: minecraft:smooth_basalt
[warning] Unknown uname: minecraft:spruce_boat
[warning] Unknown uname: minecraft:tuff
[warning] Unknown uname: minecraft:water_bucket
[warning] Unknown uname: minecraft:weathered_cut_copper_stairs
[warning] Unknown uname: minecraft:white_dye
[warning] Unknown uname: minecraft:yellow_dye

**Comment by Plidian** [comment]
So this has been resolved.  YAY!
