### ISSUE TITLE
Update docker container

### ISSUE THREAD

**Issue by vladbogun1** [bedrock-viz/bedrock-viz#113]
I am running all on my raspberry pi server, and i cant build docker by myself or compile project, i found old image https://hub.docker.com/r/dazworrall/bedrock-viz 
but it is so old... i need fresh fixes which you merged yesterday.

Can you build and share newer docker container please?

**Comment by cabbey** [comment]
so far as I know, @DazWorrall will need to update that now that v0.1.4 is out.

**Comment by DazWorrall** [comment]
I'll get a fresh version built and pushed somewhere - might even setup Actions for it.

@cabbey are the [build instructions](https://github.com/bedrock-viz/bedrock-viz/blob/master/docs/BUILD.md#ubuntu-tested-on-ubuntu-1804) out of date? I'm getting an error compiling 0.1.4:

```
/bedrock-viz/utils/legend.cc: In function 'int main(int, char**)':
/bedrock-viz/utils/legend.cc:146:34: error: 'setfill' was not declared in this scope
                 output << hex << setfill('0') << setw(6) << right << biome->colorAsLocalInt();
                                  ^~~~~~~
/bedrock-viz/utils/legend.cc:146:34: note: suggested alternative: 'setgid'
                 output << hex << setfill('0') << setw(6) << right << biome->colorAsLocalInt();
                                  ^~~~~~~
                                  setgid
/bedrock-viz/utils/legend.cc:146:50: error: 'setw' was not declared in this scope
                 output << hex << setfill('0') << setw(6) << right << biome->colorAsLocalInt();
                                                  ^~~~
/bedrock-viz/utils/legend.cc:146:50: note: suggested alternative: 'getw'
                 output << hex << setfill('0') << setw(6) << right << biome->colorAsLocalInt();
                                                  ^~~~
                                                  getw
/bedrock-viz/utils/legend.cc:189:30: error: 'setfill' was not declared in this scope
             output << hex << setfill('0') << setw(6) << right << block->colorAsLocalInt();
                              ^~~~~~~
/bedrock-viz/utils/legend.cc:189:30: note: suggested alternative: 'setgid'
             output << hex << setfill('0') << setw(6) << right << block->colorAsLocalInt();
                              ^~~~~~~
                              setgid
/bedrock-viz/utils/legend.cc:189:46: error: 'setw' was not declared in this scope
             output << hex << setfill('0') << setw(6) << right << block->colorAsLocalInt();
                                              ^~~~
/bedrock-viz/utils/legend.cc:189:46: note: suggested alternative: 'getw'
             output << hex << setfill('0') << setw(6) << right << block->colorAsLocalInt();
                                              ^~~~
                                              getw
make[2]: *** [CMakeFiles/legend.dir/utils/legend.cc.o] Error 1
```

**Comment by jhayden954** [comment]
I believe for linux you need to add:

#include <iomanip>

in /utils/legend.cc.  You can then compile successfully.

**Comment by cabbey** [comment]
Ooh, are you on an old Ubuntu image? 18.04 maybe? I had seen errors much like that on the CI tests, but bumped it up to a newer version and they went away.

If @jhayden954's suggestion works we can get it into the upstream.

**Comment by cabbey** [comment]
ok, looks like that's the ticket. I've landed that change to master and rolled the linux CI back to 18.04. @DazWorrall I'm sure if you used that commit for you 0.1.4 docker base no one would even notice. (nothing else has landed on master since.)

**Comment by DazWorrall** [comment]
I’ll try building on a newer Ubuntu too - only reason I was using 18.04 was to match the docs!

**Comment by DazWorrall** [comment]
I have updated https://hub.docker.com/r/dazworrall/bedrock-viz based on #118, if I get time I'll try to follow that up with an Actions workflow to maintain the image automatically using the GitHub image registry.

**Comment by cabbey** [comment]
Thanks to @DazWorrall I think we can call this closed.
