### ISSUE TITLE
Biomes mis-identified

### ISSUE THREAD

**Issue by tomnolan** [bedrock-viz/bedrock-viz#12]
Many biomes on the biome layer are being misidentified. I have ocean (as an example) that is being identified as end highlands or end barrens.

**Comment by picotazo** [comment]
That is a weird one mine is working fine with biomes..  what version of bedrock are you running and what version of bedrock-viz do you use? Have you customized any of it?

**Comment by tomnolan** [comment]
I just did a little digging and it looks like this is a bedrock vs java difference. Taking a look at the Data2D with Universal Minecraft Editor, I can see that biomes 42 and 43 are among an example where the map is mis-labeling things. bedrock-viz is telling me that this is end higlands and end barrens, but in Minecraft (and even on the map overview itself) I can see that this is deep ocean of some kind, I think it's actually warm deep ocean.

**Comment by picotazo** [comment]
in the mcpe_viz.xml file is the <biomelist> section  below is mine however I am currently going through it mostly line by line to verify I have everything matching what is listed here https://minecraft.gamepedia.com/Bedrock_Edition_data_values

your welcome to copy and replace yours with mine I highly recommend using something like notepadd++ compare plugin so you can see the differences between the viz.xml here and the one you are currently using.  I am not sure but I think that the xml file should really be in the root of the folder with the bedrock-viz.exe to get utilized

Peck

  <biomelist>
    <biome id="0x00" name="Ocean" color="0x8b92dd" />
    <biome id="0x01" name="Plains" color="0x1f953e" />
    <biome id="0x02" name="Desert" color="0xede586" />
    <biome id="0x03" name="Extreme Hills" color="0xa0a0a0" />
    <biome id="0x04" name="Forest" color="0x184d1e" />
    <biome id="0x05" name="Taiga" color="0x7fae7c" />
    <biome id="0x06" name="Swampland" color="0x694268" />
    <biome id="0x07" name="River" color="0x616699" />
    <biome id="0x08" name="Hell" color="0xa00000" />
    <biome id="0x09" name="The End" color="0xd1d28a" />
    <biome id="0x0a" name="Frozen Ocean" color="0x0cf5ed" />
    <biome id="0x0b" name="Frozen River" color="0xabedeb" />
    <biome id="0x0c" name="Snowy Tundra" color="0xf0f0f0" />
    <biome id="0x0d" name="Snowy Mountains" color="0xe0e0e0" />
    <biome id="0x0e" name="Mushroom Fields" color="0xff1c1c" />
    <biome id="0x0f" name="Mushroom Fields Shore" color="0xff5050" />
    <biome id="0x10" name="Beach" color="0xffd37e" />
    <biome id="0x11" name="Desert Hills" color="0xd6cd63" />
    <biome id="0x12" name="Wooded Hills" color="0x2e6535" />
    <biome id="0x13" name="Taiga Hills" color="0x8ead8c" />
    <biome id="0x14" name="Mountain Edge" color="0x909090" />
    <biome id="0x15" name="Jungle" color="0x04a51e" />
    <biome id="0x16" name="Jungle Hills" color="0x036c14" />
    <biome id="0x17" name="Jungle Edge" color="0x21ab38" />
    <biome id="0x18" name="Deep Ocean" color="0x3644d8" />
    <biome id="0x19" name="Stone Shoew" color="0x808080" />
    <biome id="0x1a" name="Snowy Beach" color="0xe0e0ff" />
    <biome id="0x1b" name="Birch Forest" color="0x8af98f" />
    <biome id="0x1c" name="Birch Forest Hills" color="0x90e294" />
    <biome id="0x1d" name="Dark Forest" color="0x1f7b23" />
    <biome id="0x1e" name="Snowy Taiga" color="0xd0d0f0" />
    <biome id="0x1f" name="Snowy Taiga Hills" color="0xa0a0c0" />
    <biome id="0x20" name="Giant Tree Taiga" color="0x45390a" />
    <biome id="0x21" name="Giant Tree Taiga Hills" color="0x76641b" />
    <biome id="0x22" name="Wooded Mountains" color="0xb0b0b0" />
    <biome id="0x23" name="Savanna" color="0x80b21f" />
    <biome id="0x24" name="Savanna Plateau" color="0x9ac548" />
    <biome id="0x25" name="Badlands" color="0xb75252" />
    <biome id="0x26" name="Wooded Badlands Plateau" color="0xb76666" />
    <biome id="0x27" name="Badlands Plateau" color="0xb87474" />
    <biome id="0x28" name="Small End Islands" color="0xd2cf7d" />
    <biome id="0x29" name="End Midlands" color="0xaaa750" />
    <biome id="0x2a" name="End Highlands" color="0xe0dd93" />
    <biome id="0x2b" name="End Barrens" color="0xaaa761" />
    <biome id="0x2c" name="Warm Ocean" color="0x838ade" />
    <biome id="0x2d" name="Lukewarm Ocean" color="0x6770cb" />
    <biome id="0x2e" name="Cold Ocean" color="0xa1a6d1" />
    <biome id="0x2f" name="Deep Warm Ocean" color="0x1c268b" />
    <biome id="0x30" name="Deep Lukewarm Ocean" color="0x2833a8" />
    <biome id="0x31" name="Deep Cold Ocean" color="0x7b7fab" />
    <biome id="0x32" name="Deep Frozen Ocean" color="0xa8aabe" />
    <biome id="0x7f" name="The Void" color="0x202020" />
    <biome id="0x80" name="Plains M" color="0x2faf51" />
    <biome id="0x81" name="Sunflower Plains" color="0xf8f12c" />
    <biome id="0x82" name="Desert Lakes" color="0xb8b270" />
    <biome id="0x83" name="Gravelly Mountains" color="0xc0c0c0" />
    <biome id="0x84" name="Flower Forest" color="0xfd893c" />
    <biome id="0x85" name="Taiga Mountains" color="0x84c280" />
    <biome id="0x86" name="Swamp Hills" color="0x936396" />
    <biome id="0x8c" name="Ice Spikes" color="0x02cffd" />
    <biome id="0x95" name="Modified Jungle" color="0x14e736" />
    <biome id="0x97" name="Modified Jungle Edge" color="0x3ada54" />
    <biome id="0x9b" name="Tall Birch Forest" color="0x9de2a0" />
    <biome id="0x9c" name="Tall Birch Hills" color="0x83bb85" />
    <biome id="0x9d" name="Dark Forest Hills" color="0x15901a" />
    <biome id="0x9e" name="Snowy Taiga Mountains" color="0x9090b0" />
    <biome id="0xa0" name="Giant Spruce Taiga" color="0x538a4d" />
    <biome id="0xa1" name="Giant Spruce Taiga Hills" color="0x576c54" />
    <biome id="0xa2" name="Gravelly Mountains+" color="0xd0d0d0" />
    <biome id="0xa3" name="Shattered Savana" color="0x96b25e" />
    <biome id="0xa4" name="Shattered Savanna Plateau" color="0x7f9652" />
    <biome id="0xa5" name="Eroded Badlands" color="0xd18383" />
    <biome id="0xa6" name="Modified Wooded Badlands Plateau" color="0xd19292" />
    <biome id="0xa7" name="Modified Badlands Plateau" color="0xb87e7e" />
    <biome id="0xa8" name="Bamboo Jungle" color="0x58d0a4" />
    <biome id="0xa9" name="Bamboo Jungle Hills" color="0x20a776" />
  </biomelist>

**Comment by tomnolan** [comment]
0x2a and 0x2b on that list are where the issue is. I'll try to post the chunk data somehow, but those are being used in overworld chunks and should be deep ocean of some kind. In fact, according to the wiki, the end biomes are java edition only, so there is definitely an issue with the biome ids not being accurate. I'm not sure how else we could find out which biome is which though since bedrock documentation is terrible.

**Comment by picotazo** [comment]
I hear ya. right now I'm having an issue with torches these for some reason on the output map they are being identified as Sunflower (top) :(

**Comment by picotazo** [comment]
Hey Tom check the colors on the different Biomes  in that section..  The issue I was having is resolved now by altering the hex color value of 1 of the 2 blocks that were being misrepresented.

**Comment by picotazo** [comment]
Tom I just check mine with the biomes and I'm seeing the same thing with the end highlands and end barrens I will do some checking.

**Comment by picotazo** [comment]
ok i change these in mine from 

biome id="0x2a" name="End Highlands" color="0xe0dd93"
biome id="0x2b" name="End Barrens" color="0xaaa761"

to
   
biome id="0x2a" name="Ocean" color="0x3644d9"
biome id="0x2b" name="Legacy Frozen Ocean" color="0x3644da"

it may not be completely accurate but it looks a whole lot better

**Comment by jasper-wan** [comment]
Sorry for the late but currently I'm working on my graduation thesis and I dont have enough time to update this repo in this year. Any contribution will be appreciated, and feel free to contact me if you want to join https://github.com/bedrock-viz

**Comment by juliankay** [comment]
I'd be interested in helping where I can!

**Comment by counterfitninja** [comment]
Would be great to get a few people here who have helped to keep it maintained into the project to help out. I'm happy to help but i have limited coding skills but can test on differing sized worlds.

**Comment by picotazo** [comment]
Same here limited coding skill but I have used the this program and its predecessor for almost 3 years now.  and I have learned a lot.   I am totally willing to help.

**Comment by amatulic** [comment]
> Sorry for the late but currently I'm working on my graduation thesis and I dont have enough time to update this repo in this year. Any contribution will be appreciated, and feel free to contact me if you want to join https://github.com/bedrock-viz

Good luck on your thesis! There are others who seem interested in providing updates but who would merge the PRs?
BTW I put an entry to this project on the Minecraft Wiki at https://minecraft.gamepedia.com/Programs_and_editors/Mapping#Map_Viewers
