### ISSUE TITLE
[  error] Unknown SubChunk palette value (value = 0)

### ISSUE THREAD

**Issue by cabbey** [bedrock-viz/bedrock-viz#126]
With v0.1.5's update to support Minecraft 1.17.30+ world block format, there are now some errors being output about an Unknown SubChunk palette value of zero. 

Currently we don't know what is in these subchunks, but there is nothing obviously missing from maps that spew hundreds of these errors. If you encounter them AND can identify what is missing in your generated map, please append information to this ticket.

**Comment by Desterly** [comment]
@cabbey - tracked this down somewhat.   not sure it's a "bug" or working as intended but the new version 9 format introduced this.   Basically if the palette value is 0, all the palette information is 0 (saves space I suppose to do it this way).

Regardless, I'm working on a fix for that

**Comment by Desterly** [comment]
Pull Request #128 should correct this

**Comment by cabbey** [comment]
This should be resolved with v0.1.6 now available. Please reopen with notes if this specific problem is still happening.
