### ISSUE TITLE
Bedrock Viz terminates unexpectedly - Windows 10. [BUG] 

### ISSUE THREAD

**Issue by mygen** [bedrock-viz/bedrock-viz#130]
Prior to the recent update, Bedrock Viz would run fine, albeit with some common NBT errors, using the default --html-most flag. Since the 0.15 release, on the same world, Bedrock Viz will run, throwing up multiple errors, and then suddenly exit before the image generation part.

I've attached a copy of the log, 

[bedrock_viz.log](https://github.com/bedrock-viz/bedrock-viz/files/7311558/bedrock_viz.log)
.
The world it is being run on is about 500Mb in size.
When I tried it on a newly created world, it ran without a hitch, which makes me believe something within the world is causing it to fail.

**Comment by Desterly** [comment]
Thanks for the world.   I was able to track down the issue and put up a pull request ( #131)

In the meantime,  I put up a debug build with the latest PR's merged in and the output world it created.  You can grab it here if you want:  https://www.dropbox.com/s/ipvisijep41gkp9/britannica_out.zip?dl=0

**Comment by cabbey** [comment]
This should be resolved with v0.1.6 now available. Please reopen with notes if this specific problem is still happening.
