### ISSUE TITLE
[BUG] Doesn't render world below y=0 or above y=255

### ISSUE THREAD

**Issue by joshhunt** [bedrock-viz/bedrock-viz#143]
**Describe the bug**

In Minecraft 1.18 the world height was raised and lowered. bedrock-viz needs updating to take that into account 

**To Reproduce**
1. Make a new Minecraft world in 1.18
2. Render --html-all world
3. See that y=0 is the lowest layer rendered

**Expected behavior**
The entire height of the world is rendered.

**Comment by cabbey** [comment]
yeah, known issue, we don't support the new Y values just yet. Should soon.

**Comment by cabbey** [comment]
resolved by 0.1.7
