### ISSUE TITLE
Lots of tiles are black - (Here be Monsters)

### ISSUE THREAD

**Issue by phunni** [bedrock-viz/bedrock-viz#144]
**Describe the bug**
Many tiles that have definitely been explored in game are showing up as black and mouseover shows (Here be Monsters - unexplored chunk). It's always been the case that there are a few "rogue" black tiles, but it's always been a small number and very easy to live with. Now, however, it's becoming so bad that it's dramatically reducing the usefulness of bedrock_viz.

For example - here is the generated map for my current game:

![screenshot](https://user-images.githubusercontent.com/11048658/144714713-dbc5f0e2-fef9-49f7-b2db-5361be6242c0.png)

And here is the in game map for the same game and area:

![Screenshot_20211203-184324](https://user-images.githubusercontent.com/11048658/144714728-8c55a5cd-6972-4ef4-98d0-e64bb12a8cd4.png)

You can see quite clearly where I have and haven't explored and the fact that, in the bedrock-viz generated map, large sections are missing.

These black sections can be removed if I explore them again - probably two or three times more - but that's not really a solution since it forces me to spend time exploring (and re-exploring) areas I already have.

**Expected behavior**
All (or the vast majority) of exploredtiles should be rendered in the map.

**Environment Information:**
 - OS: Linux
 - bedrock-viz version:  0.1.5
 - Browser (for frontend issues): Chromium

**Comment by cabbey** [comment]
This may be a limitation of the leveldb data we have available. I've noticed before that the map fills in with biome data farther from the player than the actual leveldb does... unless there's a spawner or other special structure that causes it to create the chunk. (as seen in your map output where there are all those odd single and double chunk fuzzy edges to where you've been.)

**Comment by phunni** [comment]
If it is that, then surely it's a recent change made in MC. There have always been the odd black square or extra one outside the border of the image, but they were always few. As you can see from my top image this has become *much* worse.

**Comment by counterfitninja** [comment]
There was a change to the ammount of data that was stored with 1.17.4 from memory. I noticed it on new worlds that i created. In that the area being shown in Bedrock_Viz was way less than before. So i think Cabbey is right. Mojang are now storing a smaller radius around the play for explored data as we now have much more vertical data to store. It was their way of keeping the world size lower. Which in turns shows very straight lines in the explored data on the bedrock_viz map.

**Comment by phunni** [comment]
That really suck and makes bedrock-viz much less useful - all the more annoying if it isn't even anything to do with bedrock-viz!
To be honest, I really hate the new caves and, if this isn't working properly anymore, I'm not particularly motivated to play minecraft now. :-(

**Comment by Desterly** [comment]
I haven't tried this with recent versions but IIRC, if you turn up the render distance it forces the game to load/render a greater chunk count.   It's not a "fix" but might be a workaround for initially loading chunk data while exploring maps.   

It's very possible that the updates to the "commit to db" mentioned above also impact this though,  I'll have to check that tonight.

**Comment by phunni** [comment]
Good idea - I'll play around with render distance and see if I can find a balance that helps this (if it does) and doesn't destroy performance

**Comment by counterfitninja** [comment]
I have a 72 chunk render and it does not make any difference. I mentioned this in the discord a couple of months ago. It's to keep the file size small afaik

**Comment by phunni** [comment]
I wish there was a way to tweak this - and to turn off the new giant caves...

**Comment by phunni** [comment]
So - is the conclusion that this is unfixable? If so, does that affect the future of this project?

**Comment by cabbey** [comment]
> So - is the conclusion that this is unfixable?

Yeah, I believe this is functioning as designed by Minecraft, not much we can do about it. 

>If so, does that affect the future of this project?

I don’t see that it would in any way. The type of minimal search pattern being run in this screen shot will no longer be as effective as it was, but for normal use I’m not seeing much of a difference for users that are mapping where they’ve been. My son and I have explored a number of new areas, gone spelunking in huge new caves, ventured out to find ice biomes to harvest blue ice from, etc… the maps I’ve made of new sections have a bit less fringe, but are still perfectly usable.

**Comment by cabbey** [comment]
I'm going to close this but keep it pinned as documentation for others to see if they come to report this same issue.

**Comment by ckhsponge** [comment]
I just tried exploring a world in Peaceful difficulty. About half of the chunks did not persist. After switching to Hard it's much better. I'm guessing the mobs need their state saved and cause some writes to the world.

Peaceful:
<img width="444" alt="image" src="https://user-images.githubusercontent.com/590/189814410-c51a2a48-5122-47f3-bafa-3624a210fd94.png">

Hard:
<img width="438" alt="image" src="https://user-images.githubusercontent.com/590/189815369-d7a87096-b98c-42a8-aa72-8d929b4e0e02.png">

**Comment by counterfitninja** [comment]
It's how Bedrock saves the world these days. There needs to be an update in the chunk for it to save.this Save data transfer and storage
