### ISSUE TITLE
Can't run on Ubuntu (Failed to load xml file)

### ISSUE THREAD

**Issue by Nodman** [bedrock-viz/bedrock-viz#15]
Hi! Thank you for forking and keeping this repo alive!
I am trying to use bedrock-viz on Ubuntu 18, but unfortunately getting an error:
```
[  error] xml file(/usr/local/share/bedrock-viz/data/mcpe_viz.xml) not parsed successfully: File was not found
[  error] Failed to load xml file
```

I don't understand why bedrock-viz is trying to look for the XML file in this directory, it's not even in PATH.

Trying to run like this:
```
./bedrock-viz/build/bedrock-viz --db ./temp/Goodtimes --out ./www/ --html-most --no-force-geojson
```

Thank you!

**UPDATE:**

I tried to use --xml and also tried to link XML file, so bedrock-viz could find it, but then it will keep looking for other files in the same location:
```
[  error] copyFileWithStringReplacement failed to open src (/usr/local/share/bedrock-viz/static/mcpe_viz.html.template) errno=No such file or directory(2)
[  error] copyFile failed for src (/usr/local/share/bedrock-viz/static/mcpe_viz.js) to dest (./www//mcpe_viz.js) error-code (2)
[  error] copyFile failed for src (/usr/local/share/bedrock-viz/static/mcpe_viz.css) to dest (./www//mcpe_viz.css) error-code (2)
[  error] copyDirToDir(src=/usr/local/share/bedrock-viz/static/js dest=./www//js) failed to open source directory
[   info] Copying icon images
[  error] copyDirToDir(src=/usr/local/share/bedrock-viz/static/images dest=./www//images) failed to open source directory
```

**Comment by jasper-wan** [comment]
Did you build it on your local system? Run `make install` will install all files on your /usr/local/ folder ant then run `bedrock-viz <your parameters>`
The new version was designed to be installed on your system via apt or homebrew, so it will trying to load files from a standard location, for example, `/usr/local/share`

**Comment by picotazo** [comment]
I'm using it on a windows 10 system with powershell as my command shell and notepad++  as my editor it is working pretty smooth with my setup only running into issues with certain old worlds.

**Comment by Nodman** [comment]
@jasper-wan Thank you!
