### ISSUE TITLE
Villages not identified

### ISSUE THREAD

**Issue by counterfitninja** [bedrock-viz/bedrock-viz#16]
It looks like villagers are not being identified on my map. Ill take a look at the Xml to see if there is something in there not working.

**Comment by picotazo** [comment]
villagers or "a village"

**Comment by counterfitninja** [comment]
Villagers. villages are showing up but im not seeing ay villagers within them

**Comment by picotazo** [comment]
ok let me check mine and see if they work here mainly because there are 2 different version of a villager now..

**Comment by counterfitninja** [comment]
This is a brand new world so villager_v2  not tried with the old villagers

**Comment by picotazo** [comment]
yup I think the program is only searching for the old version of villager.. let me see if I can find where the setting is to change it to look for villager_v2

**Comment by counterfitninja** [comment]
I changes the entry for villager to villager_v2 in the cfg file and they all start to show up.

**Comment by picotazo** [comment]
in the xml file?

**Comment by picotazo** [comment]
in the static directory if you edit mcpe_viz.html.template you can alter the listings

**Comment by counterfitninja** [comment]
sorry wasn't clear. i edited the entry in the mcpe_viz_xml file .. Not had a look at the mcpe_viz.html.template file to know what that is doing

**Comment by picotazo** [comment]
I updated my branch "I hope properly ".. and fixed a ton of stuff in the xml file and edited the template file to make some of the buttons work again and added other mobs to identify on the map. feel free to check it out.

**Comment by counterfitninja** [comment]
I noticed that yesterday. Glad we have some people trying to maintain it. Such a useful tool would be a shame to see it languish. Good work
