### ISSUE TITLE
are unexplored viewable chunks sometimes black?

### ISSUE THREAD

**Issue by chino** [bedrock-viz/bedrock-viz#163]
I can see a lot of details from a distance but it all shows up as black in the viz?

**Comment by geoffholden** [comment]
This is the same as issue #144 
To speed things up and to keep the world file smaller, the game doesn't save out those chunks you see from a distance to disk.

**Comment by chino** [comment]
Wow does that mean that it could literally end up seeing something different each time you look at those areas?

**Comment by geoffholden** [comment]
No, what gets generated is based on the world seed--it'll be the same every time (assuming the same Minecraft version).
