### ISSUE TITLE
[ error] LevelDB operation returned status=Corruption: CURRENT file does not end with newline (What am I doing wrong?)

### ISSUE THREAD

**Issue by mooing-cowmilk** [bedrock-viz/bedrock-viz#165]
I'm trying out this program for the first time but not having luck starting it.
I open cmd line in the folder there the exe is then I ran:
bedrock-viz --db `C:\Users\highm\AppData\Local\Packages\Microsoft.MinecraftUWP_8wekyb3d8bbwe\LocalState\games\com.mojang\minecraftWorlds\GAyuYn6dPAA=\ --out C:\Users\highm\Documents\Minecraft programs\bedrock-viz_v0.1.7_win10-64\out1 --html-all
`
Resulting in the output of:

[   info] Loading xml from (data/bedrock_viz.xml)
[   info] Loading config from (data/bedrock_viz.cfg)
[   info] parseLevelFile: name=C:\Users\highm\AppData\Local\Packages\Microsoft.MinecraftUWP_8wekyb3d8bbwe\LocalState\games\com.mojang\minecraftWorlds\GAyuYn6dPAA=\/level.dat version=8 len=2783
[   info]   Found World Spawn: x=-3813 y=203 z=502
[   info] levelname.txt: Level name is 'Copy of Copy of start Caves & Cliffs Explorers'
[   info] DB Open: dir=C:\Users\highm\AppData\Local\Packages\Microsoft.MinecraftUWP_8wekyb3d8bbwe\LocalState\games\com.mojang\minecraftWorlds\GAyuYn6dPAA=\
[   info] DB Open Status: Corruption: CURRENT file does not end with newline (block_size=4096 bloom_filter_bits=10)
[  error] LevelDB operation returned status=Corruption: CURRENT file does not end with newline
[   info] Scan keys to get world boundaries

Each varient of the command in cmd or powershell yeilds in the same error.
What am I doing wrong?

![image](https://user-images.githubusercontent.com/106852406/174452121-6e7e9bb8-8b5d-4336-a0e4-75f8b88db820.png)
![image](https://user-images.githubusercontent.com/106852406/174452142-f12c263a-4fac-4f37-a7e4-a75c4d1ebfef.png)
![image](https://user-images.githubusercontent.com/106852406/174452151-9aba5493-5f81-4e51-9536-e3f363f2f477.png)

**Comment by cabbey** [comment]
This feels like you are working from a live copy of your world while MC is running, not a backup.
