### ISSUE TITLE
Mislabeled blocks

### ISSUE THREAD

**Issue by picotazo** [bedrock-viz/bedrock-viz#20]
OK looking closer at the XML file and using my test world I am seeing many mislabeled using the original XML file. When I am using the updated XML file from my fork many missing blocks now show in the output but are still mislabeled or just don't appear if I have 1 of each slab on the ground, for example the 3 different prismarine slabs are labeled as "slab, Red Sandstone" and newer blocks like " "Cut red sandstone" and "cut sandstone" don't show up at all.  Looking at the XML it seems like it has something to do with the blocks that have block variants, like the program is ignoring the variants and only being identified as the root block. 

Another example possibly the easiest to view is wood planks all are labeled as oak planks. 

On the other hand some of the new items such as the new wooden buttons/doors/trapdoors since they are all individual Blocks they all are identified properly.

 I tired removing the main color of the item and adding the different colors for the variants they  then get labeled as "*UNKNOWN BLOCK*"

**Comment by picotazo** [comment]
OK stone blocks are all being identified as basic stone either the program is ignoring the DV/blockdata piece or it needs to be changed to look at the "stone_type" tag to determine its type.  I think the same thing goes for most other blocks that have variants. I do not know where in the program this is determined.

**Comment by counterfitninja** [comment]
Looks like concrete is doing the same thing. Ill take a look at the code and see if i can find anything but so far it all looks ok. Like you say its seems to be ignoring the blockdata

**Comment by picotazo** [comment]
Cool thank you for taking a look at it..

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

________________________________

**Comment by counterfitninja** [comment]
I dont think any of the block variants are working. It seems to be pick this first in the list and lable them all with that. Ill do some more digging.
