### ISSUE TITLE
High memory usage

### ISSUE THREAD

**Issue by counterfitninja** [bedrock-viz/bedrock-viz#22]
Hi All, 

Is everyone seeing high memory usage whilst building layers? Eventually its runs out of memory and crashes.

**Comment by picotazo** [comment]
It is still working for me. Does it do the same thing on a new very small world?


Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

**Comment by counterfitninja** [comment]
Smalls worlds are fine. I don't consider this world large either but memory is just shooting up.

**Comment by picotazo** [comment]
How large is the world and how much ram dii ok you have on your system?

Sent from my iPhone

On Mar 31, 2020, at 2:10 PM, counterfitninja <notifications@github.com> wrote:

﻿

Smalls worlds are fine. I don't consider this world large either but memory is just shooting up.

**Comment by counterfitninja** [comment]
The world is about 10mb in size. Server has 16gb ram. It's an azure machine so I can up it.

**Comment by counterfitninja** [comment]
Just double checked the world its not 10Mb at all. its 70Mb..

**Comment by picotazo** [comment]
Still that isn’t that big…  the current world I’m working with is around 140Mb and it still works.


Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

**Comment by counterfitninja** [comment]
I don't think it's the size but more the blocks. The issue is that the end is pretty big as I have flown around quite lot end raiding. Pruning the end makes the memory lower. Is there a switch to just create the over world? That would help.

**Comment by picotazo** [comment]
I am pretty sure yes or if you want to you can backup the world and then use MCC tool chest PE and delete the End dimension.

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

**Comment by counterfitninja** [comment]
I used that to prune it, but would be nice to use a switch here. That way I can do the three dimensions separately . It looks like it will just not 100% sure. On getting it Working.

**Comment by ynleborg** [comment]
Same for me. 220MB world, 16GB RAM and controlled by system swap. Tried couple of time and it always crashes around 44GB of used memory. See screenshot. 
![bedrock-viz-memory-problem](https://user-images.githubusercontent.com/510157/79622085-1f24f200-8116-11ea-8a9f-33833d669a64.jpg)

**Comment by timvandenhof** [comment]
I can confirm this issue. Tested with a 240 MB world. Runs out of memory and fails silently, even the world.log is incomplete at that moment. This is on a 4 core, 8 GB ram system running Win2019, only running windows, bedrock server and bedrock viz.

**Comment by ynleborg** [comment]
Yeah,  I gave up... and switched to https://github.com/mjungnickel18/papyruscs. I miss layer-by-layer view, but papyruscs works form my almost 400MB. You can check it here: http://necro.city.

**Comment by counterfitninja** [comment]
Tried my world which is around 140mb on a rig with 32 gb of ram to see if it would render. It worked but used a total of 19gb of ram. Sham we don't have anyone able to pick the project up and look at fundamental issues that are here. I love this project for many reasons, just wish it was actively developed.

**Comment by bazfp** [comment]
#23 This PR has fixed it. Recommend a new release to fix it. Runs fine with only 600Mb RAM consumption now on a large map, whereas before it would consume 32Gb before crashing

**Comment by counterfitninja** [comment]
Hey thats Brilliant new bazfp. Great to see someone with the time take a look. Lets hope we can get a new release soon. Do you have pre-compiled version we can test?

**Comment by bazfp** [comment]
I've attached a Windows build with the fix. Let me know if you get it running correctly.

[Release.zip](https://github.com/bedrock-viz/bedrock-viz/files/4640304/Release.zip)

**Comment by counterfitninja** [comment]
Wow.. that has certainly done the trick. My world that was using 19gb of RAM only peaked around 311mb of RAM.  Well done.

**Comment by counterfitninja** [comment]
Bwzfp, quick question as I have no idea how to contact you. Any chance you can look into the code and see if different block type is the same block type are being rendered properly. Ie coloured concrete seems to pick the first colour on the list and not enumerate round the ll other colours

**Comment by kilimar** [comment]
I have the same issue with the memory leak and came here,  It seems that Release.zip and the download from the main page is different.  For instance --log is not an option in bazfp's build.  However, using bazfp's build and trying to process a world from bedrock 1.14.60_5 (140mb), it errors out:

C:\Users\?\Downloads\release>bedrock-viz.exe --db D:\bedrock-server-1.14.60.5_WIN\worlds\Beach --out "./resort/index" --html-all --verbose
[  error] Block id=214(0xd6 name=Nether wart Block already exists
[  error] add block failed(name=Nether wart Block, id=0xd6)
[  error] blocklist parse failed
[  error] Failed to load xml file

v0.1.1_win64 (from main page), the application ran and generated data but runs out of memory and crash.  With bazfp's release, it doesn't get very far.

Anyone else have a similar problem?

**Comment by counterfitninja** [comment]
Did you use the data folder within the release. There are some issues with altered ones that 8bhace not had timed to work out yet

**Comment by kilimar** [comment]
> Did you use the data folder within the release. There are some issues with altered ones that 8bhace not had timed to work out yet

I just extracted the release.zip into it's own directory and ran it from there.  I also tried overlaying/overwriting bedrock-viz_0.1.1_win64 with release.zip and got the same error.

However, I just deleted everything, re-extracted and tried it again and it seems to be working.  Weird.
