### ISSUE TITLE
Compiling from source on ubuntu 18.04

### ISSUE THREAD

**Issue by robinfreeman** [bedrock-viz/bedrock-viz#24]
Was just trying to compile on a fresh AWS image of Ubuntu 18.04 and was getting the following during

`cmake ..`

```
CMake Error at /usr/share/cmake-3.10/Modules/FindPackageHandleStandardArgs.cmake:137 (message):
  Could NOT find PNG (missing: PNG_LIBRARY PNG_PNG_INCLUDE_DIR)
```

Installing libpng got it working:

`sudo apt-get install libpng++-dev`

**Comment by tomnolan** [comment]
Thanks, I'll get the build.md updated to reflect the dependency.
