### ISSUE TITLE
No GUI from .exe and HTML page links do not go anywhere

### ISSUE THREAD

**Issue by roblee357** [bedrock-viz/bedrock-viz#25]
Hello. When I run this command: 
bedrock-viz_v0.1.1_win64>bedrock-viz.exe --no-force-geojson --db "C:\Users\roble\AppData\Local\Packages\Microsoft.MinecraftUWP_8wekyb3d8bbwe\LocalState\games\com.mojang\minecraftWorlds\PWfOXo6uRwA=/" --out out1 --html-all
I see a new out1.geojson and out1.html but no images. And the links in the HTML file do not do anything.
Here is the console output:
Packages\Microsoft.MinecraftUWP_8wekyb3d8bbwe\LocalState\games\com.mojang\minecraftWorlds\PWfOXo6uRwA=/" --out out1 --html-all
Reading XML from data/mcpe_viz.xml
parseLevelFile: name=C:\Users\roble\AppData\Local\Packages\Microsoft.MinecraftUWP_8wekyb3d8bbwe\LocalState\games\com.mojang\minecraftWorlds\PWfOXo6uRwA=//level.dat version=8 len=2081
  Found World Spawn: x=4 y=32767 z=12
  Level name is [The best place to live and wor]
DB Open: dir=C:\Users\roble\AppData\Local\Packages\Microsoft.MinecraftUWP_8wekyb3d8bbwe\LocalState\games\com.mojang\minecraftWorlds\PWfOXo6uRwA=/
DB Open Status: OK (block_size=4096 bloom_filter_bits=10)
Scan keys to get world boundaries
  Bounds (chunk): DimId=0 X=(-18 19) Z=(-13 16)
  Bounds (pixel): DimId=0 X=(-288 304) Z=(-208 256) Image=(608 480)
  Bounds (chunk): DimId=1 X=(0 0) Z=(0 0)
  Bounds (pixel): DimId=1 X=(0 0) Z=(0 0) Image=(16 16)
  Bounds (chunk): DimId=2 X=(0 0) Z=(0 0)
  Bounds (pixel): DimId=2 X=(0 0) Z=(0 0) Image=(16 16)
  4350 records
Active 'hide-top', 'force-top', and 'geojson-block':
None
Parse all leveldb records
INFO: Unmapped remote player: 20b87a14-9120-35a9-9e98-9b6278fd7f65
INFO: Unmapped remote player: 5e5281d1-ee65-3a59-a1be-e2d8bc82837b
INFO: Unmapped remote player: server_49e3de99-cfa6-47f9-acd7-e7aaedc85105
Player Position: Dimension=0 Pos=(-7.42362, 59.62, 16.1678 @ image 280, 224) Rotation=(-81.712891, -0.327026)
Read 4350 records
Status: OK
Check Spawnable: Dimension 'overworld' (0)
Check Spawnable: Dimension 'nether' (1)
Check Spawnable: Dimension 'the-end' (2)
Do Output: overworld
  Generate Image
    Info: World (0, 0) is at image (288, 208)
    Info: World Spawn (4, 12) is at image (292, 220)
  Generate Biome Image
  Generate Grass Image
  Generate Height Column Image
  Generate Height Column (grayscale) Image
  Generate Height Column (alpha) Image
  Generate Block Light Image
  Generate Sky Light Image
  Generate Slime Chunks Image
  Generate Shaded Relief Image
  Generate full-size slices
    Writing all images in one pass
    Row 0 of 480
    Row 320 of 480
Do Output: nether
  Generate Image
  Generate Biome Image
  Generate Grass Image
  Generate Height Column Image
  Generate Height Column (grayscale) Image
  Generate Height Column (alpha) Image
  Generate Block Light Image
  Generate Sky Light Image
  Generate Slime Chunks Image
  Generate Shaded Relief Image
  Generate full-size slices
    Writing all images in one pass
    Row 0 of 16
Do Output: the-end
  Generate Image
  Generate Biome Image
  Generate Grass Image
  Generate Height Column Image
  Generate Height Column (grayscale) Image
  Generate Height Column (alpha) Image
  Generate Block Light Image
  Generate Sky Light Image
  Generate Slime Chunks Image
  Generate Shaded Relief Image
  Generate full-size slices
    Writing all images in one pass
    Row 0 of 16
Do Output: html viewer
Done.

**Comment by tomnolan** [comment]
@roblee357 did you build from source or are you running this from the most recent release that's here? Are you still having this issue?

**Comment by roblee357** [comment]
At the time of this post I had downloaded the zip file, unzipped it, and tried running the command. Yes, I've not had any success yet. Thanks Tom. -Rob
