### ISSUE TITLE
Ref #25 Dead links and no images.

### ISSUE THREAD

**Issue by roblee357** [bedrock-viz/bedrock-viz#39]
I'm still having the same issue.  I do not see the images and the links go no where. 

C:\Users\roble\Downloads\bedrock-viz_v0.1.1_win64 (1)>bedrock-viz.exe --no-force-geojson --db "C:\Users\roble\AppData\Local\Packages\Microsoft.MinecraftUWP_8wekyb3d8bbwe\LocalState\games\com.mojang\minecraftWorlds\NUsWXbvtQgA=" --out out3 --html-most
Reading XML from data/mcpe_viz.xml
parseLevelFile: name=C:\Users\roble\AppData\Local\Packages\Microsoft.MinecraftUWP_8wekyb3d8bbwe\LocalState\games\com.mojang\minecraftWorlds\NUsWXbvtQgA=/level.dat version=8 len=2121
  Found World Spawn: x=1028 y=32767 z=4
  Level name is [NICKLE]
DB Open: dir=C:\Users\roble\AppData\Local\Packages\Microsoft.MinecraftUWP_8wekyb3d8bbwe\LocalState\games\com.mojang\minecraftWorlds\NUsWXbvtQgA=
DB Open Status: OK (block_size=4096 bloom_filter_bits=10)
Scan keys to get world boundaries
  Bounds (chunk): DimId=0 X=(0 98) Z=(-16 46)
  Bounds (pixel): DimId=0 X=(0 1568) Z=(-256 736) Image=(1584 1008)
  Bounds (chunk): DimId=1 X=(0 0) Z=(0 0)
  Bounds (pixel): DimId=1 X=(0 0) Z=(0 0) Image=(16 16)
  Bounds (chunk): DimId=2 X=(0 0) Z=(0 0)
  Bounds (pixel): DimId=2 X=(0 0) Z=(0 0) Image=(16 16)
  22436 records
Active 'hide-top', 'force-top', and 'geojson-block':
None
Parse all leveldb records
  Processing records: 10000 / 22436 (44.6%)
  Processing records: 20000 / 22436 (89.1%)
INFO: Unmapped remote player: 20b87a14-9120-35a9-9e98-9b6278fd7f65
INFO: Unmapped remote player: 5e5281d1-ee65-3a59-a1be-e2d8bc82837b
INFO: Unmapped remote player: 853eabc6-e011-308f-9d65-5ce75f24842a
INFO: Unmapped remote player: f3ffaf8c-58c1-33ef-8583-1189c4421855
INFO: Unmapped remote player: server_adacfe5e-0f47-49f0-b0c3-f293d2e5c20f
INFO: Unmapped remote player: server_b44d8f21-8df4-44fc-8142-0ab1793c6fcf
Player Position: Dimension=0 Pos=(1190.7, 65.62, 261.3 @ image 1190, 517) Rotation=(41.245667, 0.979797)
Read 22436 records
Status: OK
Check Spawnable: Dimension 'overworld' (0)
Check Spawnable: Dimension 'nether' (1)
Check Spawnable: Dimension 'the-end' (2)
Do Output: overworld
  Generate Image
    Info: World Spawn (1028, 4) is at image (1028, 260)
  Generate Biome Image
  Generate Grass Image
  Generate Height Column Image
  Generate Height Column (grayscale) Image
  Generate Height Column (alpha) Image
  Generate Block Light Image
  Generate Sky Light Image
  Generate Slime Chunks Image
  Generate Shaded Relief Image
Do Output: nether
  Generate Image
  Generate Biome Image
  Generate Grass Image
  Generate Height Column Image
  Generate Height Column (grayscale) Image
  Generate Height Column (alpha) Image
  Generate Block Light Image
  Generate Sky Light Image
  Generate Slime Chunks Image
  Generate Shaded Relief Image
Do Output: the-end
  Generate Image
  Generate Biome Image
  Generate Grass Image
  Generate Height Column Image
  Generate Height Column (grayscale) Image
  Generate Height Column (alpha) Image
  Generate Block Light Image
  Generate Sky Light Image
  Generate Slime Chunks Image
  Generate Shaded Relief Image
Do Output: html viewer
Done.

**Comment by tomnolan** [comment]
Based on the output you pasted here, it looks like you are using an older version of the app. Try with the latest release and let us know if it still isn't working.

**Comment by roblee357** [comment]
That was correct. I used the link in the quick start section which was for the 1.1 version. Now I see the images and the HTML renders. 
However I get the CORS error even in Firefox.
Error accessing map pixels.

Error: SecurityError: The operation is insecure.

Bedrock Viz Hint: If you are loading files from the local filesystem, your browser might not be allowing us to load additional files or examine pixels in maps. Firefox does not have this limitation. See README for more info...

**Comment by tthorntone** [comment]
@roblee357 I also had this issue. Firefox also seems to have an issue these days-- looks like they hardened their "Same Origin" Policy. Easiest way to get around this (on Windows, but should be pretty easily changed for other envs) that i've found is:
1. Make a shortcut on your Desktop for Chrome.
2. Right click on the shortcut -> properties. 
3. In the "Target" box, add this to the end: "--disable-web-security --user-data-dir="C:\Users\USER_NAME\Documents\Chrome"
3a. Make sure to replace USER_NAME with your actual path.
4. Apply
5. Close out of chrome, all windows, and right click the icon in the taskbar shortcuts all the way to the right, and exit there too.
6. Run the shortcut, then open the html page in this instance of chrome.

**Comment by jasper-wan** [comment]
you could run a web server with python, just type:

```
python -m http.server
```
in the output folder

**Comment by edward3h** [comment]
Another option for a local web server is running this docker: https://hub.docker.com/r/halverneus/static-file-server/

I use it with this wrapper script: 
`$ cat ~/bin/localweb
#!/bin/bash

docker run -d \
    -v "$PWD":/web \
    -p 8666:8080 \
    halverneus/static-file-server:latest`

**Comment by tomnolan** [comment]
I'm going to mark this one resolved since the original issue has been dealt with. The issue with the security error is something else that we are hoping to fix in a UI update that is planned. That issue can be tracked in #46
