### ISSUE TITLE
Unkonwn unames

### ISSUE THREAD

**Issue by killercode** [bedrock-viz/bedrock-viz#4]
Hello
When I was generating my map the following warning appeared?

[warning] Unknown uname: minecraft:barrel
[warning] Unknown uname: minecraft:bee_nest
[warning] Unknown uname: minecraft:bell
[warning] Unknown uname: minecraft:blast_furnace
[warning] Unknown uname: minecraft:campfire
[warning] Unknown uname: minecraft:cartography_table
[warning] Unknown uname: minecraft:composter
[warning] Unknown uname: minecraft:crossbow
[warning] Unknown uname: minecraft:double_stone_slab4
[warning] Unknown uname: minecraft:grindstone
[warning] Unknown uname: minecraft:lectern
[warning] Unknown uname: minecraft:smoker
[warning] Unknown uname: minecraft:smooth_stone
[warning] Unknown uname: minecraft:spruce_wall_sign
[warning] Unknown uname: minecraft:stone_slab4
[warning] Unknown uname: minecraft:stonecutter_block
[warning] Unknown uname: minecraft:sweet_berries
[warning] Unknown uname: minecraft:sweet_berry_bush
[warning] Unknown uname: minecraft:wood

Is there anyway I can help updating these?

Thanks

**Comment by jasper-wan** [comment]
Those are new items and blocks in bedrock 1.13 and 1.14. Add these missing uname to data/mcpe_viz.xml will fill these warnings.
