### ISSUE TITLE
Villagers not displaying. 

### ISSUE THREAD

**Issue by counterfitninja** [bedrock-viz/bedrock-viz#45]
Its looks like villagers are still not displaying on the latest build.

**Comment by paulgrahek** [comment]
Villager IDs did change with the Village and Pillage update. This has likely not been reflected in the code.

**Comment by paulgrahek** [comment]
We are working on updating the UI right now, but if you want to have the villagers show up now you can go into `index.html` in the output or `bedrock_viz.html.template` in the code and change 
``` html
<li><a href="#" class="entityToggle" data-type="P" data-id="15">Villager</a></li>
```
to
``` html
<li><a href="#" class="entityToggle" data-type="P" data-id="15">Villager(Old)</a></li>
<li><a href="#" class="entityToggle" data-type="P" data-id="115">Villager</a></li>
```
