### ISSUE TITLE
When generating map in windows with "--htlm-all"   switch the html viewer is not added

### ISSUE THREAD

**Issue by johnall203** [bedrock-viz/bedrock-viz#5]
Hello,  

Glad someone picked up mcpe_viz and got it upto date.  I have been using Plethora's version for several years.  So I was testing using your program by command line as I got use to using the GUI "mcpe_viz_helper.exe" to generate my maps and I can not get the --html-all switch to output the html viewer.  It stops right after "processing records:" and just terminates to command prompt. I do get an images directory but only has each of the world levels in it.  None of the other image files.  The switch "--hml-most" seems to be working because it exports all the extra files.  So I took notice of what was different between the two outputs and here is what is missing when html-all is executed:

  Processing records: 260000 / 266664 (97.5%)   ((( this is as far as --html-all gets and then stops)))
Read 266664 records   ((( when running html-most it goes further and does the rest like below.)))
Status: OK
Check Spawnable: Dimension 'overworld' (0)
Check Spawnable: Dimension 'nether' (1)
Check Spawnable: Dimension 'the-end' (2)
Do Output: overworld
  Generate Image
    Info: World (0, 0) is at image (5904, 12784)
    Info: World Spawn (12, 4) is at image (5916, 12788)
  Generate Biome Image
  Generate Grass Image
  Generate Height Column Image
  Generate Height Column (grayscale) Image
  Generate Height Column (alpha) Image
  Generate Block Light Image
  Generate Sky Light Image
  Generate Slime Chunks Image
  Generate Shaded Relief Image
Do Output: nether
  Generate Image
  Generate Biome Image
  Generate Grass Image
  Generate Height Column Image
  Generate Height Column (grayscale) Image
  Generate Height Column (alpha) Image
  Generate Block Light Image
  Generate Sky Light Image
  Generate Slime Chunks Image
  Generate Shaded Relief Image
Do Output: the-end
  Generate Image
  Generate Biome Image
  Generate Grass Image
  Generate Height Column Image
  Generate Height Column (grayscale) Image
  Generate Height Column (alpha) Image
  Generate Block Light Image
  Generate Sky Light Image
  Generate Slime Chunks Image
  Generate Shaded Relief Image
Detected large images and 'auto-tile' is enabled, enabling tiles!
Creating tiles for out1.overworld.map.png...
Creating tiles for out1.overworld.biome.png...
Creating tiles for out1.overworld.height_col.png...
Creating tiles for out1.overworld.height_col_grayscale.png...
Creating tiles for out1.overworld.height_col_alpha.png...
Creating tiles for out1.overworld.light_block.png...
Creating tiles for out1.overworld.light_sky.png...
Creating tiles for out1.overworld.slime_chunks.png...
Creating tiles for out1.overworld.grass.png...
Creating tiles for out1.overworld.shaded_relief.png...
Creating tiles for out1.nether.map.png...
Creating tiles for out1.nether.biome.png...
Creating tiles for out1.nether.height_col.png...
Creating tiles for out1.nether.height_col_grayscale.png...
Creating tiles for out1.nether.height_col_alpha.png...
Creating tiles for out1.nether.light_block.png...
Creating tiles for out1.nether.light_sky.png...
Creating tiles for out1.nether.slime_chunks.png...
Creating tiles for out1.nether.grass.png...
Creating tiles for out1.nether.shaded_relief.png...
Creating tiles for out1.the-end.map.png...
Creating tiles for out1.the-end.biome.png...
Creating tiles for out1.the-end.height_col.png...
Creating tiles for out1.the-end.height_col_grayscale.png...
Creating tiles for out1.the-end.height_col_alpha.png...
Creating tiles for out1.the-end.light_block.png...
Creating tiles for out1.the-end.light_sky.png...
Creating tiles for out1.the-end.slime_chunks.png...
Creating tiles for out1.the-end.grass.png...
Creating tiles for out1.the-end.shaded_relief.png...
Do Output: html viewer
Copying icon images
Done.

C:\>

Can you fix the --html-all  ? It seems to be just missing the html viewer processing at the end.

Thank you,
John

**Comment by picotazo** [comment]
does it do the same thing when using a fresh world? I have several older worlds that just wont load in mcpe-viz or bedrock-viz anymore due to one thing or another. But loading a new barely explored world does work.  Can you give me the gist of the command line your using? Mine is basically:

.\bedrock-viz.exe --no-force-geojson --db "C:/Users/Desktop/minecraftWorlds/realm" --out "C:/Users/Desktop/minecraftWorlds/Output/realm/realm" --html-all

I had to download version 62.0 of firefox to make the web view work with the layers. however I have noticed that is is working with Microsoft Edge Version 44.18362.449.0

**Comment by timvandenhof** [comment]
Can confirm, same issue here. Html and javascript files are missing. Seems like something crashes, but not sure about that yet.

Currently investigating a workaround: ``--html -all-image --no-force-geojson --slices``

**Comment by counterfitninja** [comment]
How large are the worlds? New ish worlds work fine but there is a massive memory leakage that stop the process dead with no errors.

**Comment by tomnolan** [comment]
@johnall203 are you able to build from source? I believe this was fixed in one of the recent updates with the memory leak fix and some of the other bits. I'll be posting a new release once I finish the nether update stuff if you aren't able to build from source.
