### ISSUE TITLE
Windows BUILD.md instructions fail. Can't locate zlib.  

### ISSUE THREAD

**Issue by aj4m2a** [bedrock-viz/bedrock-viz#53]
This section of BUILD.md which gives instructions on how to build the repopsitory under Windows
`
# make
mkdir build
cd build
cmake .. -DCMAKE_TOOLCHAIN_FILE=<path-to-vcpkg>/scripts/buildsystems/vcpkg.cmake -G "Visual Studio 16 2019" -A x64

`
results in the following error

`CMake Error at C:/Program Files/CMake/share/cmake-3.17/Modules/FindPackageHandleStandardArgs.cmake:164 (message):
  Could NOT find ZLIB (missing: ZLIB_LIBRARY ZLIB_INCLUDE_DIR)
Call Stack (most recent call first):
  C:/Program Files/CMake/share/cmake-3.17/Modules/FindPackageHandleStandardArgs.cmake:445 (_FPHSA_FAILURE_MESSAGE)
  C:/Program Files/CMake/share/cmake-3.17/Modules/FindZLIB.cmake:115 (FIND_PACKAGE_HANDLE_STANDARD_ARGS)
  third_party/leveldb/CMakeLists.txt:47 (find_package)

-- Configuring incomplete, errors occurred!
See also "C:/Users/Simon/Documents/GitHub/bedrock-viz/build/CMakeFiles/CMakeOutput.log".
See also "C:/Users/Simon/Documents/GitHub/bedrock-viz/build/CMakeFiles/CMakeError.log".
`

[CMakeError.log](https://github.com/bedrock-viz/bedrock-viz/files/4914009/CMakeError.log)
[CMakeOutput.log](https://github.com/bedrock-viz/bedrock-viz/files/4914010/CMakeOutput.log)

**Comment by paulgrahek** [comment]
Let's get that issue figured out! Could you provide the output from your vcpkg install, using `vcpkg list`?

**Comment by aj4m2a** [comment]
Thanks for the "good first issue" label. it would appear premature. I have started from a clean sheet and now cannot reproduce the error. Please close the issue. Sorry.
