### ISSUE TITLE
[BUG] Unknown unames in error log

### ISSUE THREAD

**Issue by aj4m2a** [bedrock-viz/bedrock-viz#64]
**Describe the bug**
The following warnings are produced at the end of a run

[warning] Unknown uname: minecraft:netherite_boots
[warning] Unknown uname: minecraft:netherite_chestplate
[warning] Unknown uname: minecraft:netherite_helmet
[warning] Unknown uname: minecraft:netherite_leggings
[warning] Unknown uname: minecraft:polished_andesite_stairs
[warning] Unknown uname: minecraft:smooth_stone
[warning] Unknown uname: minecraft:spruce_wall_sign
[warning] Unknown uname: minecraft:stone_stairs

It appears that these items are missing from the data/bedrock-viz.xml file.

**Comment by cabbey** [comment]
i believe these are all resolved with v0.1.3
