### ISSUE TITLE
Please Help [Closed]

### ISSUE THREAD

**Issue by DeeFeeCee** [bedrock-viz/bedrock-viz#65]
I cannot figure out how to make this program run. Typing "bedrock-viz.exe --db bluh\bluh --out out1 --html-all" does absolutely nothing. The README suggests there's a user interface like MCPE Viz, but there is no such "helper" in the folder. I'm getting really stressed out by the ambiguous wording of "run it something like this" & "do something like this". Do I type this into command prompt? Do I need to run as admin? Can I type anything into bedrock-viz.exe before it closes? Is there a helper?

I don't even know where to type "./bedrock-viz --help", since Command Prompt just gives me '[anything I attempt to type]' is not recognized as an internal or external command,
operable program or batch file. I'm at my wit's end.

**Comment by IDemixI** [comment]
Hi @DeeFeeCee,

So here are the steps I woudl follow:

- Download the latest release from [here](https://github.com/bedrock-viz/bedrock-viz/releases/)
- Extract the folder somewhere safe, for this example, I'm going to say pop it in C:\bedrock-viz-0.1.2
- Now open a command prompt (CMD) and type `cd C:\bedrock-viz-0.1.2` - This puts you in the right folder.
- Now you're able to type `bedrock-viz.exe --db C:\folder\your\world\is\in --outdir C:\bedrock-viz-0.1.2\worldname --html-all`

That should do the trick! 👍
