### ISSUE TITLE
"Could not load file: images/bedrock_viz.overworld.map.png" 

### ISSUE THREAD

**Issue by vejinnovem** [bedrock-viz/bedrock-viz#66]
I'm pretty sure that this is due to my overworld map being a little bit too big.
And I mean, like 50000x30000. Mostly because of going faaaaaar west and faaaar north once upon a time what generated places where no one on my server even wants to go no more.
This causes my map not loading in 'overworld' mode and showing this when entering my http:
"Could not load file: images/bedrock_viz.overworld.map.png"
I checked out miniweb, apache and nginx, with all the troubleshooting for not loading pngs I could find.
PNGs are not corrupted, I can load them with file browser.
Though I can't load them by entering whole path to one png in Chrome, like:
http://myserver/images/bedrock_viz.overworld.shaded_relief.png" (this one is the largest file, containing 55MB)
The only thing my browser shows then is a little empty square.
Firefox shows a big empty gray image when I enter this path.
(I wish I could set a certain coordinates for rendering map but maybe it's something else I can work out)
I almost forgot. End and Nether are loading fine. Mostly because these PNGs are far smaller than the Overworld one.

**Comment by vejinnovem** [comment]
Response for other people who get map that big with only one adventure:
I didn't know I could reset that chunks with MCCToolChestPE.
Now my map is a lot smaller than before and everything works.
Thanks anyway for BedrockViz. I love it.

**Comment by cabbey** [comment]
This issue should be resolved by change #44 in the next release which changes to using tiled images by default.
![Screenshot of approximately 32k x 32k world mapped with current git head build](https://user-images.githubusercontent.com/522147/103146917-ca099900-4704-11eb-9c54-6ab91d85d938.png)

**Comment by cabbey** [comment]
Fixed in v0.1.3
