### ISSUE TITLE
Show village centers

### ISSUE THREAD

**Issue by elplatt** [bedrock-viz/bedrock-viz#69]
**Is your feature request related to a problem? Please describe.**
In order to optimize iron golem spawning, I need to know where the village center is.

**Describe the solution you'd like**
I would like village centers to be displayed as entities, ideally with the Y coordinate displayed.

**Describe alternatives you've considered**
Possibly indicating a village center visually when viewing that layer.

**Additional context**
In bedrock, iron golems spawn in a volume centered on the village center (a bell, bed, or job site block). If a villager links to the block and fails to pathfind to it, it results in a new block being chosen as the village center, which can result in unpredictability and failure of iron golems to spawn. Knowing where the village center is would make it possible to debug village and iron farm designs.

It is also worth noting that there can be overlapping villages, so it would be especially helpful to have a way to tell which village a villager/bed is linked to.

**Comment by johnall203** [comment]
That would be a nice feature.   Village dynamics seem to be buggy at times.  More information could help.

**Comment by elplatt** [comment]
I might be able to help implement this, although I'd need to be pointed to the right part of the code.

**Comment by DeeFeeCee** [comment]
There is NBT data in the form of 4 sections: VILLAGE_..._DWELLERS, VILLAGE_..._INFO, VILLAGE_..._PLAYERS, & VILLAGE_..._POI. The first POI (found in VILLAGE_..._POI) indicates the center of the village if & only if there are no other POIs outside the 64*24*64 area centered on that POI. The actual center can be calculated from VILLAGE_..._INFO, wherein there are values X0, X1, Y0, Y1, Z0, & Z1. All you have to do is find the arithmetic mean between each pair of values & you have the center.

**Comment by DeeFeeCee** [comment]
It's also worth noting that the village center tends to change between loads, so that's a uh, "feature" in MCBE.

**Comment by cmbkla** [comment]
On the list of Objects to show/hide, Villages is an option. That thing has never shown anything for me -- does that show anything for anyone else? Looking at the code, it seems like it's kind of intended to show villages (which implies it "knows" the center already), just haven't seen that feature work.
