### ISSUE TITLE
[BUG] Overworld map is blank

### ISSUE THREAD

**Issue by benubu** [bedrock-viz/bedrock-viz#80]
**Describe the bug**
Overworld map is blank. I've made sure it's centered. I've turned on displaying mobs, objects etc. to show there's data. But there's no actual map.

Nether and The End maps are fine.

Images are there in the images folder of the output.

I've tried opening the file directly, installing a local webserver and running through that (xampp), and uploading to a hosted webserver (dreamhost). Same result on each. 

I'm running Windows 10. I downloaded and installed the pre-compiled binary for bedrock-viz 1.2

**Screenshots**
Screenshot of blank map.
![image](https://user-images.githubusercontent.com/74571551/99316253-e3234e00-2818-11eb-9ae8-93a0981b15e0.png)

And here's the file rendered for overworld, altitude 255 (compressed .zip archive, native .png was too large to upload)

[bedrock_viz.slice.full.overworld.255.zip](https://github.com/bedrock-viz/bedrock-viz/files/5550127/bedrock_viz.slice.full.overworld.255.zip)

Any ideas how to resolve this?

**Comment by cabbey** [comment]
given the size of the world shown in your screen shot, I suspect your mapped world is pretty huge. #44 changed to use tiled worlds by default, which should resolve this in the next release. In the interim you could use the command line options to switch to tiled.
![Screenshot of approximately 32k x 32k world mapped with current git head build](https://user-images.githubusercontent.com/522147/103146917-ca099900-4704-11eb-9c54-6ab91d85d938.png)

**Comment by cabbey** [comment]
Fixed in v0.1.3
