### ISSUE TITLE
[BUG] images/bedrock_viz.overworld.map.png

### ISSUE THREAD

**Issue by KnowinglyUnknown** [bedrock-viz/bedrock-viz#82]
Creating a large file generally causes the overworld map to stall

1.go in a diagonal line for 10000+ blocks in a world
2.Use the app to create the map
3.load index.html

an image should form

![image](https://user-images.githubusercontent.com/64538745/101044203-0b9d9d00-35ba-11eb-93c7-23a04dde64ac.png)

 - OS: Windows
 - bedrock-viz version: v0.1.2 (latest)
 - Browser: Google Chrome

**Comment by cabbey** [comment]
This will be resolved in the next release due to the change to use tiles by default under #44 
![Screenshot of approximately 32k x 32k world mapped with current git head build](https://user-images.githubusercontent.com/522147/103146917-ca099900-4704-11eb-9c54-6ab91d85d938.png)

**Comment by cabbey** [comment]
Fixed in v0.1.3
