### ISSUE TITLE
[BUG] Firefox gives the issue of CORS error

### ISSUE THREAD

**Issue by KnowinglyUnknown** [bedrock-viz/bedrock-viz#83]
![image](https://user-images.githubusercontent.com/64538745/101055633-0db92900-35c5-11eb-8cea-68c6be7a6368.png)

**Environment Information:**
 - OS: Windows
 - bedrock-viz version: 0.2.1
 - Browser: Firefox

**Comment by savvasdalkitsis** [comment]
You might want to try serving the files via a local web server instead of loading them as a local file. 

I found a nice gist explaining your options here: https://gist.github.com/jgravois/5e73b56fa7756fd00b89

**Comment by KnowinglyUnknown** [comment]
That documentation is old, do you have a newer one? Otherwise, I need a step by step help.

**Comment by KnowinglyUnknown** [comment]
also while you are here, can you teach me how to bring the out1 file out of my C:/Users/User file

**Comment by KnowinglyUnknown** [comment]
Thank you
