### ISSUE TITLE
[BUG]  Error Trying to Install on 2020 MacBook Air (M1 Processor)

### ISSUE THREAD

**Issue by hugoanderson5** [bedrock-viz/bedrock-viz#95]
**Describe the bug**
When I try to install bedrock-viz using homebrew on a 2020 MacBook Air with an M1 processor, I get the following error:

```
==> Summary
🍺  /opt/homebrew/Cellar/libxml2/2.9.10_2: 280 files, 10.9MB
==> Installing bedrock-viz/tap/bedrock-viz
==> cmake ..
Last 15 lines from /Users/Hugo/Library/Logs/Homebrew/bedrock-viz/01.cmake:
-- Performing Test COMPILER_HAS_DEPRECATED_ATTR - Success
-- Build spdlog: 1.5.0
-- Build type: Release
-- Found PNG: /opt/homebrew/lib/libpng.dylib (found version "1.6.37") 
CMake Error at /opt/homebrew/Cellar/cmake/3.19.2/share/cmake/Modules/FindPackageHandleStandardArgs.cmake:218 (message):
  Could NOT find Boost (missing: Boost_INCLUDE_DIR program_options)
Call Stack (most recent call first):
  /opt/homebrew/Cellar/cmake/3.19.2/share/cmake/Modules/FindPackageHandleStandardArgs.cmake:582 (_FPHSA_FAILURE_MESSAGE)
  /opt/homebrew/Cellar/cmake/3.19.2/share/cmake/Modules/FindBoost.cmake:2193 (find_package_handle_standard_args)
  CMakeLists.txt:52 (find_package)
```

I've attached the full log.
[log.txt](https://github.com/bedrock-viz/bedrock-viz/files/5791234/log.txt)

**Comment by mikeamcbrien** [comment]
I also received this message on a non-M1 MacBook pro (2019)...
`==> Summary
🍺  /usr/local/Cellar/libxml2/2.9.10_2: 280 files, 10.6MB
==> Installing bedrock-viz/tap/bedrock-viz
==> cmake ..
Last 15 lines from /Users/mike/Library/Logs/Homebrew/bedrock-viz/01.cmake:
-- Performing Test COMPILER_HAS_DEPRECATED_ATTR - Success
-- Build spdlog: 1.5.0
-- Build type: Release
-- Found PNG: /usr/local/lib/libpng.dylib (found version "1.6.37") 
CMake Error at /usr/local/Cellar/cmake/3.19.4/share/cmake/Modules/FindPackageHandleStandardArgs.cmake:218 (message):
  Could NOT find Boost (missing: Boost_INCLUDE_DIR program_options)
Call Stack (most recent call first):
  /usr/local/Cellar/cmake/3.19.4/share/cmake/Modules/FindPackageHandleStandardArgs.cmake:582 (_FPHSA_FAILURE_MESSAGE)
  /usr/local/Cellar/cmake/3.19.4/share/cmake/Modules/FindBoost.cmake:2193 (find_package_handle_standard_args)
  CMakeLists.txt:52 (find_package)


-- Configuring incomplete, errors occurred!
See also "/tmp/bedrock-viz-20210215-11403-o5i0i6/build/CMakeFiles/CMakeOutput.log".
See also "/tmp/bedrock-viz-20210215-11403-o5i0i6/build/CMakeFiles/CMakeError.log".

If reporting this issue please do so at (not Homebrew/brew or Homebrew/core):
  https://github.com/bedrock-viz/homebrew-tap/issues
`

**Comment by mikeamcbrien** [comment]
FYI @hugoanderson5 Installing Boost first resolved my errors... 

`brew install boost`

**Comment by hugoanderson5** [comment]
Huzzah! That fixed it for me, thanks @mikeamcbrien!
