### ISSUE TITLE
[BUG] dll missing and after that Entry Point missing

### ISSUE THREAD

**Issue by Sacki666** [bedrock-viz/bedrock-viz#97]
**Describe the bug**
programm is starting on W10 with error message "VCRUNTIME140_1.dll not found". After placing a renamed VCRUNTIME140.dll into the program folder a second error message comes up with entrypoint --CxFrameHandler4 not found in s-vc142-mt-x64-1_75.dll

**To Reproduce**
1. download latest Win_X64 version
2. run from Commandline or doubleclick

**Expected behavior**
a starting program :-)

**Screenshots**
![image](https://user-images.githubusercontent.com/78081859/105983883-a639ca00-6099-11eb-9fee-99eeef9c0be3.png)

![image](https://user-images.githubusercontent.com/78081859/105983774-830f1a80-6099-11eb-92b2-042ee1c17fd1.png)

**Environment Information:**
 - OS: Win 10 pro German
 - bedrock-viz version: latest win version (v0.1.3_win64)

**Comment by CoderMarcus** [comment]
I mean, for me it doesn't even show an error message, just crashes instantly.

**Comment by cabbey** [comment]
can you confirm that the previous build, v0.1.2 worked for you?

**Comment by CoderMarcus** [comment]
> can you confirm that the previous build, v0.1.2 worked for you?

No, build v0.1.2 also doesn't work.

**Comment by Sacki666** [comment]
Hi Cabbey,
yes 0.1.2 is runnig and after transfering the (missing) dll files to the 0.1.3 folder the actual one is also working. Good job and thanks.

Greeting Matthias

@CoderMarcus please make your own issue, your problems are not the same. Maybe you should read the using instructions, this is not a form based application, you have to unse the commandline. ;-)
