### ISSUE TITLE
center of map missing

### ISSUE THREAD

**Issue by Squirrelthug** [bedrock-viz/bedrock-viz#98]
**Describe the bug**
After rendering the map and opening in browsers I got the error for why some images may not load. I have now uploaded it to a server to view and the error is gone but the center of the map is still not rendered. Hovering over those blocks labels them as air or undiscovered. As I mouse over it seems anything I had discovered on the map in the center is being replaced by air and not being rendered

**To Reproduce**
1. Link unavailable'

**Expected behavior**
a fully rendered map

**Screenshots**

**Environment Information:**
 - OS: win10 x64
 - bedrock-viz version: 0.0.48
 - Browser (for frontend issues): chrome/firefox
 - Build toolchain information (if applicable): 

**Additional context**
I had the files uploaded to Amazon's AWS service but I needed to upload a working map so that link is now broken. The issue was replicated in a render from papyrusCs but running the script on a new download fixed the issue for papyrusCs, but not for MCPEviz.

**Comment by counterfitninja** [comment]
Have you tried zooming out or click the E button on the left side of the page to render the entire map?

**Comment by cabbey** [comment]
we're going to need a weee bit more to go on here. I don't suppose you could zip up the output and send it to us?  Also just to double check, since you reference MCPEviz... you were running with Bedrock Viz, right?
